export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';
export const GET_DANH_SACH_NGUOI_DUNG = 'GET_DANH_SACH_NGUOI_DUNG';
export const SET_THONG_TIN_TAI_KHOAN = 'SET_THONG_TIN_TAI_KHOAN'